# Generated by Django 5.1.2 on 2024-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_skillexchange_is_paid_service_skillexchange_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
