# Generated by Django 5.1.2 on 2024-10-19 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0003_userprofile_profile_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillexchange",
            name="is_paid_service",
        ),
        migrations.RemoveField(
            model_name="skillexchange",
            name="offered_by",
        ),
        migrations.RemoveField(
            model_name="skillexchange",
            name="price",
        ),
        migrations.RemoveField(
            model_name="skillexchange",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="skillexchange",
            name="skills_offered",
        ),
        migrations.RemoveField(
            model_name="skillexchange",
            name="skills_requested",
        ),
        migrations.RemoveField(
            model_name="skillexchange",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="skillexchange",
            name="initiator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_exchanges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skillexchange",
            name="target",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targeted_exchanges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="skillexchange",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
